name: Build docker image and model

on:
  push:
    branches:
      - develop

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: praekeltfoundation/tbconnect-bot
          tag_with_ref: true
          tag_with_sha: true
