name: Run tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bot: ['base']
        lang: ['eng', 'afr', 'xho', 'sot', 'zul']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -r requirements-actions.txt
      - name: Test
        run: |
          ./test.sh ${{ matrix.bot }} ${{ matrix.lang }}
